name: Zapusk skripta s id

on: 
  workflow_dispatch:
  # schedule:
    # - cron: '*/5 * * * *'

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd anime_get
        npm install

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: anime_get/id.txt
        key: id-cache-${{ runner.os }}-${{ github.workflow }}
        restore-keys: |
          id-cache-${{ runner.os }}-

    - name: Run script
      run: |
        cd anime_get
        node script.js

    - name: Save cache
      uses: actions/cache@v3
      with:
        path: anime_get/id.txt
        key: id-cache-${{ runner.os }}-${{ github.workflow }}
